set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g status-keys vi
setw -g mode-keys vi
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -sel clip -i'

unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# This allows me to rename the windows without them getting renamed back, like
# my fixed NOTES window
set-option -g allow-rename off


set -g status-position bottom
# set -g status-style "bg=#57864E,fg=#FFFFEC"
set -g status-style "bg=#FFFFEC,fg=#57864E"
