[global]
username = gustavogiordanocolombini@gmail.com
password_cmd = bw get item 979a6561-bea0-4bd5-a3dd-a94a0145d5ef | grep -oP 'password\"\:\"\K[^"]*'
device_name = Spotifyd@tardis
device_type = computer
bitrate = 320
cache_path = /home/tretinha/.cache
no_audio_cache = false
