#!/bin/sh

dir=$HOME/Pictures/Screenshots
mkdir -p "$dir"
out=$dir/$(date -Is).png

case "$1" in
-r)
	grim -g "$(slurp -db '#44444480')" "$out" || exit 1
	;;
*)
	grim "$out" || exit 1
	;;
esac

wl-copy < "$out"
notify-send -t 3000 "Screenshot saved" "$out"
