#!/bin/sh

lock='swaylock -f -i ~/Pictures/wallpaper.jpg --scaling fill'

exec swayidle -w \
	timeout 270 'notify-send -t 30000 "Locking screen in 30 seconds"' \
	timeout 300 "$lock" \
	timeout 600 'swaymsg "output * power off"' \
		resume 'swaymsg "output * power on"' \
	before-sleep "$lock"
